MODEL:
    architecture: 'tsvit'
    img_res: 24
    max_seq_len: 60
    num_channels: 11
    num_classes: 19
    dropout_prob: 0.
    patch_size: 2
    embed_size: 128
    embed_dropout_prob: 0.
    temporal_depth: 4
    spatial_depth: 4
    num_heads: 4
    forward_dropout_prob: 0.
    forward_scale: 4

DATASETS:
    train:
        dataset_name: 'PASTIS24'
        root_dir: '/pgeoprj/godeep/ewab/datasets/PASTIS24'
        csv_path: '/pgeoprj/godeep/ewab/datasets/PASTIS24/fold-paths/folds_1_123_paths.csv'
        max_seq_len: 60
        batch_size: 16
        num_workers: 2
    
    val:
        dataset_name: 'PASTIS24'
        root_dir: '/pgeoprj/godeep/ewab/datasets/PASTIS24'
        csv_path: '/pgeoprj/godeep/ewab/datasets/PASTIS24/fold-paths/fold_4_paths.csv'
        max_seq_len: 60
        batch_size: 24
        num_workers: 2
    
    test:
        dataset_name: 'PASTIS24'
        root_dir: '/pgeoprj/godeep/ewab/datasets/PASTIS24'
        csv_path: '/pgeoprj/godeep/ewab/datasets/PASTIS24/fold-paths/fold_5_paths.csv'
        max_seq_len: 60
        batch_size: 24
        num_workers: 2

SOLVER:
    num_epochs: 100
    num_warmup_epochs: 10
    start_epoch: 1
    loss_function: 'cross_entropy'
    class_weights:
    ignore_index: 19
    # lr_scheduler: 'cosine'
    lr_base: 1e-3
    lr_min: 5e-6
    # lr_start: 1e-8
    weight_decay: 0.000

CHECKPOINT:
    load_from_checkpoint:
    save_path: 'experiments'
    train_metrics_steps: 250
    eval_steps: 2000